### ISSUE TITLE
Dockerfile tries to ADD missing tar files

### ISSUE THREAD

**Issue by londonbrown** [JetBrains/ide-services-docker#1]
[The Dockerfile fails to build as it expects the local repository to have `tbe-*.tar` files](https://github.com/JetBrains/toolbox-enterprise-docker/blob/main/Dockerfile#L34), however none are provided in the repository. 

```
ADD tbe-*.tar /app/
Error response from daemon: ADD failed: no source files were specified
```

Where can we obtain the necessary `tbe-*.tar` files?

**Comment by MarcinAman** [comment]
Fixed in https://github.com/JetBrains/toolbox-enterprise-docker/pull/2
